export const metadata: Metadata = {
  title: "Create Next App",
  description: "A Next.js app generated by Create Next App",
  keywords: ["Next.js", "App", "PDF Books", "Search Engine", "Programmable Search Engine"],
  author: "Your Name", // String instead of an object
  creator: "Your Name",
  robots: "index, follow", 
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://www.yourwebsite.com",
    siteName: "Create Next App",
    images: [
      {
        url: "https://www.yourwebsite.com/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "Create Next App OG Image",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    site: "@yourtwitterhandle",
    title: "Create Next App",
    description: "Generated by create next app",
    image: "https://www.yourwebsite.com/images/og-image.png",
  },
};
